### ISSUE TITLE
Cannot find fuse3 on arch linux

### ISSUE THREAD

**Issue by hartmark** [FilenCloudDienste/filen-network-drive#28]
**Describe the bug**
Seems the program cannot correctly that fuse3 is installed.

**To Reproduce**
```
wget https://github.com/FilenCloudDienste/filen-cli/releases/download/v0.0.12/filen-cli-v0.0.12-linux-x64
chmod +x filen-cli-v0.0.12-linux-x64

./filen-cli-v0.0.12-linux-x64
# enter username and password

filen-cli-v0.0.12-linux-x64 mount filen
Mounting network drive for mail@hartmark.se at X:
FUSE 3 is needed in Linux for network drive mounting. FUSE 3 could not be found.

% pacman -Ql fuse3
fuse3 /usr/
fuse3 /usr/bin/
fuse3 /usr/bin/fusermount3
fuse3 /usr/bin/mount.fuse3
fuse3 /usr/include/
fuse3 /usr/include/fuse3/
fuse3 /usr/include/fuse3/cuse_lowlevel.h
fuse3 /usr/include/fuse3/fuse.h
fuse3 /usr/include/fuse3/fuse_common.h
fuse3 /usr/include/fuse3/fuse_log.h
fuse3 /usr/include/fuse3/fuse_lowlevel.h
fuse3 /usr/include/fuse3/fuse_opt.h
fuse3 /usr/include/fuse3/libfuse_config.h
fuse3 /usr/lib/
fuse3 /usr/lib/libfuse3.so
fuse3 /usr/lib/libfuse3.so.3
fuse3 /usr/lib/libfuse3.so.3.16.2
fuse3 /usr/lib/pkgconfig/
fuse3 /usr/lib/pkgconfig/fuse3.pc
fuse3 /usr/lib/udev/
fuse3 /usr/lib/udev/rules.d/
fuse3 /usr/lib/udev/rules.d/99-fuse3.rules
fuse3 /usr/share/
fuse3 /usr/share/man/
fuse3 /usr/share/man/man1/
fuse3 /usr/share/man/man1/fusermount3.1.gz
fuse3 /usr/share/man/man8/
fuse3 /usr/share/man/man8/mount.fuse3.8.gz
```

**Expected behavior**
The program should be able to find fuse3

**OS (please complete the following information):**
Arch linux

**Comment by Dwynr** [comment]
Can you try again with the latest release of the CLI (https://github.com/FilenCloudDienste/filen-cli/releases/latest)? We've updated the internal dependencies.

Otherwise this is due to the `which` command not being available on Arch by default. I'll add an extra check using `pacman` just in case.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-network-drive/commit/cc805b2ae55eae29b89620f6d45ce73b90235693

**Comment by hartmark** [comment]
Yes it seems to be working now. I get this errror now.
```
markus@staropramen ~ % filen-cli-v0.0.14-linux-x64 mount filen
Mounting network drive for ***@**** at filen
Error trying to execute mount command: Cannot mount to a directory outside of your home directory.
Error: Cannot mount to a directory outside of your home directory.
    at NetworkDrive.start (/snapshot/filen-cli/dist/bundle.js)
    at async DriveMountingInterface.invoke (/snapshot/filen-cli/dist/bundle.js)
    at async /snapshot/filen-cli/dist/bundle.js

```
if I just use the same directory but as with an absolute path it accepts it
```
130 markus@staropramen ~ % filen-cli-v0.0.14-linux-x64 mount ~/filen
Mounting network drive for **@*** at /home/markus/filen
Mounted

```

Then again, why is there a limitation that the mounted directory must be in the home directory?

**Comment by Dwynr** [comment]
This is expected, the underlying logic only accepts absolute paths. For now only home directory mounts are supported due to permissions. This way we can avoid any admin permissions for mounting/unmounting. We'll consider adding a switch case for non-home directory mounts using sudo in the future.

Again, thanks for reporting the previous issue. I'll leave this issue closed for now.
